# Copyright 2024 MedSBOM Contributors
# SPDX-License-Identifier: Apache-2.0

"""Core data models for MedSBOM."""

from __future__ import annotations

import enum
from datetime import date, datetime
from typing import Any

from pydantic import BaseModel, Field


class SBOMFormat(enum.StrEnum):
    """Supported SBOM formats."""

    CYCLONEDX = "cyclonedx"
    SPDX = "spdx"


class RiskLevel(enum.StrEnum):
    """Risk classification levels."""

    NONE = "none"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Component(BaseModel):
    """A software component extracted from an SBOM."""

    name: str
    version: str = ""
    purl: str = ""
    license: str = ""
    supplier: str = ""
    component_type: str = "library"

    @property
    def identifier(self) -> str:
        """Return the best available identifier (purl or name@version)."""
        if self.purl:
            return self.purl
        if self.version:
            return f"{self.name}@{self.version}"
        return self.name


class Finding(BaseModel):
    """A vulnerability or risk finding for a component."""

    cve_id: str = ""
    cvss_score: float = 0.0
    cvss_vector: str = ""
    severity: str = ""
    description: str = ""
    kev_flag: bool = False
    kev_date_added: str = ""
    eol_date: date | None = None
    eos_date: date | None = None
    risk_level: RiskLevel = RiskLevel.NONE
    source: str = ""


class ComponentResult(BaseModel):
    """A component with all its findings and computed risk."""

    component: Component
    findings: list[Finding] = Field(default_factory=list)
    overall_risk: RiskLevel = RiskLevel.NONE
    eol_date: date | None = None
    eos_date: date | None = None
    is_eol: bool = False


class SBOMScan(BaseModel):
    """A complete SBOM scan with all results."""

    scan_id: str = ""
    device_name: str = ""
    device_version: str = ""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    sbom_format: SBOMFormat = SBOMFormat.CYCLONEDX
    source_tool: str = ""
    components: list[Component] = Field(default_factory=list)
    results: list[ComponentResult] = Field(default_factory=list)
    raw_sbom: dict[str, Any] = Field(default_factory=dict)


class AuditEntry(BaseModel):
    """An immutable audit log entry."""

    entry_id: str = ""
    scan_id: str = ""
    action: str = ""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    actor: str = "medsbom-cli"
    details: str = ""


# --- Regulatory disclaimer embedded in every generated document ---

REGULATORY_DISCLAIMER = (
    "DISCLAIMER: This document was auto-generated by MedSBOM, an open-source tool. "
    "It is intended as a DRAFT to assist with FDA/IEC-62304 compliance documentation. "
    "This output does NOT constitute legal or regulatory advice. All generated content "
    "must be reviewed and approved by a qualified regulatory professional before "
    "submission to any regulatory body. MedSBOM contributors accept no liability "
    "for regulatory decisions made based on this output."
)
